### ISSUE TITLE
#Fix: Reformat the ucr sql linkage script to take the sql url as a parameter to the function

### ISSUE THREAD

**Issue by J-glove** [uf-hobi-informatics-lab/SPACESCANS#48]
Currently gets set within the script - want the user to be able to specify where the SQL db is located, as it could be different for each person.

**Comment by chengrong-us** [comment]
Done! 
1. Reformatted the ucr sql linkage script to take the sql url as a parameter to the function.
2. Adjusted the parameters in the main() function to accommodate future API integrations or command-line usage.
3. Made some revisions for more generalization.
4. Revised the save function to support multiple linkages and enable iterative saving without overwriting previous data.
5. Pushed the db_linkage_ucr.py for review instead of pulling request.

**Comment by J-glove** [comment]
@chengrong-us , please create the pull request. Thank you

**Comment by chengrong-us** [comment]
Pull request completed.
